Repository prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE, pull requests merged in 2025-02, with the labels that each got.

#128 [FEAT] 좋아요 알람 게시글 표시 및 이동 기능 구현
  .github/workflows/lighthouse.yml
  src/features/notification/notification.dto.ts
  src/features/notification/ui/NoticeItem.module.scss
  src/features/notification/ui/NoticeItem.tsx
  src/features/search/ui/SearchBar.module.scss
  src/shared/util/setTextEllipsis.ts
  src/widgets/Layout/ui/Header/Header.module.scss
  src/widgets/Layout/ui/Header/Header.tsx
  src/widgets/NoticeContainer/NoticeContainer.module.scss
  src/widgets/NoticeContainer/NoticeContainer.tsx
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#127 [Feat] 채팅방 생성및 요청 기능
  package.json
  src/app/ModalProvider.tsx
  src/features/chatting/api/chatting.api.ts
  src/features/chatting/api/chatting.dto.ts
  src/features/chatting/api/chatting.hook.ts
  src/features/chatting/api/chatting.socket.ts
  src/features/chatting/api/types.ts
  src/features/chatting/model/mock.ts
  src/features/chatting/ui/ChatRoomItem.tsx
  src/features/gathering/ui/GatheringCard/GatheringCard.tsx
  src/features/notification/notification.type.ts
  src/features/notification/ui/NoticeItem.tsx
  src/features/portfolio/ui/ContactBtn.tsx
  src/features/portfolio/ui/PortfolioCard.tsx
  src/shared/model/modalStore.ts
  src/widgets/ChattingModal/ChattingModal.module.scss
  src/widgets/ChattingModal/ChattingModal.tsx
  src/widgets/ChattingModal/index.ts
  src/widgets/ChattingModal/ui/ChattingModal.module.scss
  src/widgets/ChattingModal/ui/ChattingModal.tsx
  src/widgets/ContactModal/ui/ContactModal.tsx
  src/widgets/GatheringGrid/GatheringGrid.tsx
  src/widgets/MainGatheringGrid/MainGatheringGrid.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#132 [FEAT] vite 번들 분리 및 highlight.js dynamic import 적용
  package.json
  src/features/archive/ui/MarkdownPreview.tsx
  src/features/gathering/ui/GatheringMarkdownPreview.tsx
  src/shared/lib/mark.ts
  src/shared/model/hljsLangList.ts
  vite.config.ts
  yarn.lock
Labels: 🐞 BugFix, ✨ Feature

#137 Dev Merge
  .gitignore
  package.json
  src/app/App.tsx
  src/app/appRouter.tsx
  src/features/archive/ui/MarkdownPreview.tsx
  src/features/gathering/lib/hooks/useInfiniteGatheringId.ts
  src/features/gathering/model/dto/gathering.dto.ts
  src/features/gathering/ui/GatheringMarkdownEditor.tsx
  src/features/gathering/ui/GatheringMarkdownPreview.tsx
  src/pages/GatheringDetailPage/GatheringDetailPage.tsx
  src/pages/GatheringListPage/GatheringListPage.tsx
  src/shared/lib/mark.ts
  src/shared/model/hljsLangList.ts
  src/shared/ui/MarkdownEditor/MarkdownEditor.tsx
  src/widgets/UserContents/UserContents.tsx
  vite.config.ts
  yarn.lock
Labels: 🌏 Deploy
